# Generated by Django 5.2.1 on 2025-05-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='reputation',
        ),
        migrations.AddField(
            model_name='character',
            name='is_npc',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='missionstep',
            name='success_response',
            field=models.TextField(blank=True, help_text='Narrative response shown when this step is completed'),
        ),
        migrations.AddField(
            model_name='zone',
            name='fallback_message',
            field=models.TextField(blank=True, help_text='Fallback response when a command fails in this zone'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuctionReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_earnings', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
            ],
            options={
                'ordering': ['-reputation', '-total_earnings'],
            },
        ),
        migrations.CreateModel(
            name='CharacterReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_reputations', to='core.character')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_from_players', to='core.character')),
            ],
            options={
                'unique_together': {('character', 'npc')},
            },
        ),
        migrations.CreateModel(
            name='RuinItemDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_chance', models.FloatField(help_text='Chance from 0.0 to 1.0')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('ruin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_drops', to='core.ruin')),
            ],
            options={
                'unique_together': {('ruin', 'item')},
            },
        ),
        migrations.DeleteModel(
            name='RankingEntry',
        ),
    ]
